### ISSUE TITLE
[Question] Offline package installation

### ISSUE THREAD

**Issue by meraj-kashi** [cloudymax/pxeless#30]
Hi!
This is a question and not an issue!

Is there any way to install debian packages before creating the ISO? Ubuntu cloud-init needs access to the Internet to install packages, so I am looking for a solution to inject packages during image creation.

Downloading debian packages and injecting through extras file could be a solution, but managing package dependecies is not easy!

The another possible solution could be chroot, but in which step of the script I should do?

Br,
Meraj

**Comment by cloudymax** [comment]
PXEless doesn't support this at the moment, but if that feature were to be included the location would be [here](https://github.com/cloudymax/pxeless/blob/0d8dd68fe87fa864094158d0902ba0c929ebdf77/image-create.sh#L377) 

I would recommend following [this guide](https://dev.to/otomato_io/how-to-create-custom-debian-based-iso-4g37) as it was the source material i followed while writing the squashfs part of the script.

I hope that helps! 👋

**Comment by meraj-kashi** [comment]
Thank you for your clarification.

The issue resolved. For those who are interested to install packages during image creation:
- Create a bash script (for example `offline-config.sh`) including all package installation and pre-installed configuration.
- Put the script in `extras` directory (Directory includes extra files to be added to the image)
- Add the below line to [here](https://github.com/cloudymax/pxeless/blob/develop/image-create.sh#L378):
```
log " - Step 3.5. Package customizing..."
sudo chroot squashfs-root/ /bin/bash /media/offline-config.sh
```
