### ISSUE TITLE
Release ISOs are not valid more than a day.

### ISSUE THREAD

**Issue by ghost** [cloudymax/pxeless#50]
Hi, 

thanks for picking up the slack after [covertsh/ubuntu-autoinstall-generator](https://github.com/covertsh/ubuntu-autoinstall-generator) died.

My issue: *Even if I choose to download a release, `-r` it will be kept with a filename including the download data and will not be picked up the following day.*

I have some ready, wait for it.

**Comment by cloudymax** [comment]
thanks for finding this 🙏

**Comment by ghost** [comment]
@cloudymax thanks for picking up the slack on the autoinstaller.
